apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: client-chassis
spec:
  selector:
    matchLabels:
      app: client-chassis
  template:
    metadata:
      labels:
        app: client-chassis
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: worker1
                operator: In
                values:
                - "true"
      containers:
        - name: client-chassis
          image: xiaoliang/client-chassis:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9000

---
apiVersion: v1
kind: Service
apiVersion: v1
metadata:
  name: client-chassis
spec:
  selector:
    app: client-chassis
  ports:
  - protocol: TCP
    name: http
    port: 9000
    nodePort: 9000
  type: NodePort
  externalIPs: ['192.168.43.80']
