apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gochassis-client
spec:
  selector:
    matchLabels:
      app: gochassis-client
  template:
    metadata:
      labels:
        app: gochassis-client
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 50
            preference:
              matchExpressions:
              - key: worker1
                operator: In
                values:
                - "true"
      containers:
        - name: gochassis-client
          image: perf-test/go-chassis-client:latest
          imagePullPolicy: IfNotPresent
          env:
          - name: PORT
            value: "8502"
          - name: SAMPLE_FOLDER
            value: "/root"
          - name: TARGET
            value: http://gochassis-server:9002
          ports:
            - containerPort: 8502

---
apiVersion: v1
kind: Service
apiVersion: v1
metadata:
  name: gochassis-client
spec:
  selector:
    app: gochassis-client
  ports:
  - protocol: TCP
    name: http
    port: 8502
    nodePort: 8502
  type: NodePort
