apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gohttp-server
spec:
  selector:
    matchLabels:
      app: gohttp-server
  template:
    metadata:
      labels:
        app: gohttp-server
      annotations:
        sidecar.mesher.io/inject: "yes"
        sidecar.mesher.io/discoveryType: "sc"
        sidecar.istio.io/inject: "false"
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 50
            preference:
              matchExpressions:
              - key: worker2
                operator: In
                values:
                - "true"
      containers:
        - name: gohttp-server
          image: perf-test/go-http-server:latest
          imagePullPolicy: IfNotPresent
          env:
          - name: http_proxy
            value: http://127.0.0.1:30101/
          ports:
            - containerPort: 9000

---
apiVersion: v1
kind: Service
apiVersion: v1
metadata:
  name: gohttp-server
spec:
  selector:
    app: gohttp-server
  ports:
  - protocol: TCP
    name: http
    port: 9000
    nodePort: 9000
  type: NodePort
