apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gorestful-server
spec:
  selector:
    matchLabels:
      app: gorestful-server
  template:
    metadata:
      labels:
        app: gorestful-server
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: worker1
                operator: In
                values:
                - "true"
      containers:
        - name: gorestful-server
          image: perf-test/go-restful-server:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9001

---
apiVersion: v1
kind: Service
apiVersion: v1
metadata:
  name: gorestful-server
spec:
  selector:
    app: gorestful-server
  ports:
  - protocol: TCP
    name: http
    port: 9001
    nodePort: 9001
  type: NodePort
