apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gochassis-server
spec:
  selector:
    matchLabels:
      app: gochassis-server
  template:
    metadata:
      labels:
        app: gochassis-server
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 50
            preference:
              matchExpressions:
              - key: worker2
                operator: In
                values:
                - "true"
      containers:
        - name: gochassis-server
          image: perf-test/go-chassis-server:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9002
---
apiVersion: v1
kind: Service
apiVersion: v1
metadata:
  name: gochassis-server
spec:
  selector:
    app: gochassis-server
  ports:
  - protocol: TCP
    name: http
    port: 9002
    nodePort: 9002
  type: NodePort
